name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v3

      - name: ⚙️ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # 👇 Désactive le cache des dépendances (sinon erreur lock file)
          cache: 'none'

      - name: 🧩 Install dependencies (ignore lock file)
        run: |
          npm install --legacy-peer-deps || true

      - name: 📱 Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🏗️ Build Android APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: 📦 Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Rapport_de_vol_Tunisair
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
