name: Build Android Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🔑 Setup Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/my-release-key.jks

      - name: 🏗️ Build Release APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=app/my-release-key.jks \
                                    -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
                                    -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
                                    -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }} \
                                    --no-daemon --stacktrace

      - name: 📦 Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Rapport_de_vol_Tunisair-Release-${{ github.run_number }}-${{ github.sha }}
          path: android/app/build/outputs/apk/release/app-release.apk
          
